name: Reusable pipeline
on:
  workflow_call:
    inputs:
      runs_on:
        default: "ubuntu-latest"
        description: "The runner to use for this job"
        type: string

      environment:
        default: "dev"
        description: "The environment being run on"
        type: string

    secrets:
        aws-role-arn:
            description: "Secrets to use for this job"
            required: true

jobs:
  deploy:
    name: "Dockerfile deploy"
    runs-on: ${{ inputs.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - run: make deploy ENV=${{ inputs.environment }}
